uploads = []
outputs = []

[[generated]]
id = "DUqnLdyFaT7bu1aOnJ_0V"
uri = "file://artifacts/autonxt/public/images/product-ev-platform.png"
type = "image"
title = "High tech EV chassis platform"

[[generated]]
id = "QCxsWPDcbpzU7e2XFQS5r"
uri = "file://artifacts/autonxt/public/images/product-battery.png"
type = "image"
title = "Next gen solid state battery"

[[generated]]
id = "KwUUHNr-aM86jaKfYSM7s"
uri = "file://artifacts/autonxt/public/images/product-autonomous.png"
type = "image"
title = "Autonomous driving sensor array"

[[generated]]
id = "1OHITjWUd-HoGsoh4CCr6"
uri = "file://artifacts/autonxt/public/images/gallery-1.png"
type = "image"
title = "Futuristic car interior dashboard"

[[generated]]
id = "sP5zl7kfddF7b8MFX2ogL"
uri = "file://artifacts/autonxt/public/images/gallery-2.png"
type = "image"
title = "Advanced automated car factory"

[[generated]]
id = "zO3uAQHjrym7qJvAvzGf5"
uri = "file://artifacts/autonxt/public/images/gallery-3.png"
type = "image"
title = "Electric semi truck driving"

[[generated]]
id = "2mu5vBtNSnBxJQ18yjlaW"
uri = "file://artifacts/autonxt/public/images/gallery-4.png"
type = "image"
title = "Electric bus in city night"

[[generated]]
id = "9K6KVCRoRacRkaZugAsC8"
uri = "file://artifacts/autonxt/public/images/gallery-5.png"
type = "image"
title = "EV charging station supercharger"
