kind = "web"
previewPath = "/"
title = "Autonxt"
version = "1.0.0"
id = "artifacts/autonxt"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19245

[services.development]
run = "pnpm --filter @workspace/autonxt run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/autonxt", "run", "build" ]
publicDir = "artifacts/autonxt/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19245"
BASE_PATH = "/"
